export { default as Notice } from './Notice'
export { default as Navbar} from  './Navbar'
export { default as Hero } from './Hero'
export { default as Concept } from './Concept'
export { default as Products } from './Products'
export { default as Trial } from './Trial'
export { default as Footer } from './Footer'